name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Nuxt to Github Pages
        uses: garraflavatra/nuxt-gh-pages-yarn@1.1.2
        with:
          # Your username
          username: garraflavatra
          # Your reponame
          reponame: thundercalculator
          # Your Github token
          token: ${{ secrets.GITHUB_TOKEN }}
          # Your git commit email
          gitemail: # optional, default is CI@example.com
          # Your git commit name
          gitname: # optional, default is CI
          # Your git commit message
          gitmsg: # optional, default is deploy
          # Your custom domain
          cname: # optional, default is none