name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Nuxt to Github Pages
        uses: garraflavatra/nuxt-gh-pages-yarn@1.1.2
        with:
          username: garraflavatra
          reponame: thundercalculator-vue
          token: ${{ secrets.GITHUB_TOKEN }}
          gitemail: romein@vburen.eu
          gitname: Romein van Buren
          gitmsg: Deploy
